version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testtask
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION_URL: 'postgresql://postgres:postgres@db/testtask'

volumes:
  postgres_data:
